name: data_inteface_impl
description: реализация интерфесов для получения данных из модуля data.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  data:
    path: ../data
  hive_flutter: ^1.1.0
  dio: ^4.0.4
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  hive_generator: ^1.1.1
